import { useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import {
  Chip,
  IconButton,
  styled,
  TextField,
  Tooltip,
  Typography,
} from "@mui/material";

import { useFieldArrayWithId } from "@/hooks/useFieldArrayWithId";
import EurekaIcon from "../icon/EurekaIcon";
import LabeledInput from "../labeled-input/LabeledInput";
import Link from "../link/Link";
import Spacer from "../spacer/Spacer";

/**
 * @typedef {Object} FieldArrayItemRHF
 * @property {string} listGeneratedId - Unique id generated by react-hook-form for each array item.
 */

/**
 * @typedef {import("react-hook-form").UseFieldArrayReturn<
 *   import("react-hook-form").FieldValues,
 *   string,
 *   "listGeneratedId"
 * >} UseFieldArrayReturnRHF
 */

const ContainerStyled = styled("div")(({ theme }) => ({
  "@keyframes ripplePulse": {
    "0%": {
      transform: "scale(1)",
      opacity: 1,
    },
    "100%": {
      transform: "scale(1.5)",
      opacity: 0,
    },
  },
  "& .input-area-wrapper": {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(2),
    "& .input-area": {
      flex: 1,
    },
    "& .add-button-pulse": {
      position: "relative",
      color: theme.palette.primary.dark,
      "&::after": {
        content: '""',
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: "50%",
        border: `0.5px solid ${theme.palette.primary.main}`,
        animation: "ripplePulse 1s ease-out 3",
      },
    },
  },
  "& .items-display": {
    marginTop: theme.spacing(3),
  },
  "& .items-chips": {
    display: "flex",
    flexWrap: "wrap",
    gap: theme.spacing(1),
  },
  "& .items-list": {
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(2),
    " & .item-row": {
      width: "100%",
      display: "flex",
      gap: theme.spacing(2),
      alignItems: "center",
      "& .item-value": {
        flex: 1,
      },
      "& .actions": {
        flexShrink: 0,
      },
    },
  },
}));

/**
 *
 * @param {Object} props
 * @param {(arrayMethods: UseFieldArrayReturnRHF) => React.ReactNode} props.children - Render prop receiving field array methods
 * @param {string} props.name - Name of the field array
 * @returns
 */
export default function FormArray({ children, name }) {
  const arrayMethods = useFieldArrayWithId({
    name,
  });
  return <ContainerStyled>{children(arrayMethods)}</ContainerStyled>;
}

/**
 *
 * @param {Object} props
 * @param {string} props.label - Input label
 * @param {string} props.placeholder - Input placeholder
 * @param {import("react-hook-form").UseFieldArrayInsert} props.insert
 * @returns
 */
function FormArrayTextInput({ label, placeholder, insert }) {
  const { t } = useTranslation();
  const [isValid, setIsValid] = useState(false);

  const inputRef = useRef(null);

  const handleValidation = (e) => {
    const inputValue = e.target.value ?? "";
    const inputValid = inputValue.trim() !== "";
    setIsValid(inputValid);
  };

  const handleInsert = () => {
    if (inputRef.current) {
      const value = inputRef.current.value;
      if (value.trim() !== "") {
        insert(0, value);
        inputRef.current.value = "";
      }
    }
  };

  return (
    <FormArrayInputWrapper
      helper={t("form.array.helper.text")}
      isValid={isValid}
      onAdd={handleInsert}
    >
      <LabeledInput label={label}>
        <TextField
          placeholder={placeholder}
          inputRef={inputRef}
          fullWidth
          onChange={handleValidation}
        />
      </LabeledInput>
    </FormArrayInputWrapper>
  );
}

/**
 *
 * @param {Object} props
 * @param {string} props.label - Input label
 * @param {string} props.labelPlaceholder - Placeholder for the label input
 * @param {string} props.urlPlaceholder - Placeholder for the URL input
 * @param {boolean} props.isLabelRequired - Whether the label input is required
 * @param {import("react-hook-form").UseFieldArrayInsert} props.insert - Insert method from useFieldArray
 * @returns
 */
function FormArrayURLInput({
  label,
  labelPlaceholder,
  urlPlaceholder,
  isLabelRequired,
  insert,
}) {
  const { t } = useTranslation();
  const [errors, setErrors] = useState({});
  const [submits, setSubmits] = useState(0);
  const [isValid, setIsValid] = useState(false);

  const labelRef = useRef(null);
  const urlRef = useRef(null);

  const computeIsValid = () => {
    const labelValue = labelRef.current?.value ?? "";
    const urlValue = urlRef.current?.value ?? "";
    const labelValid = !isLabelRequired || labelValue.trim() !== "";
    const urlValid = urlValue.trim() !== "";
    setIsValid(labelValid && urlValid);
  };

  const labelPlaceholderText = isLabelRequired
    ? labelPlaceholder
    : labelPlaceholder + ` (${t("form.optional")})`;

  const handleInsert = () => {
    setSubmits((prev) => prev + 1);

    const newErrors = {};

    if (!labelRef.current || !urlRef.current) {
      return;
    }

    const labelValue = labelRef.current?.value ?? "";
    if (isLabelRequired) {
      if (!labelValue || labelValue.trim() === "") {
        newErrors.title = t("validation.label_required");
      }
    }

    const urlValue = urlRef.current.value;
    if (!urlValue || urlValue.trim() === "") {
      newErrors.url = t("validation.url_required");
    }

    setErrors(newErrors);
    if (Object.keys(newErrors).length > 0) {
      return;
    }

    const value = { title: labelValue, url: urlValue };

    insert(0, value);
    labelRef.current.value = "";
    urlRef.current.value = "";
  };

  const validateLabel = (e) => {
    computeIsValid();
    if (submits === 0) return;

    const value = e.target.value;
    if (isLabelRequired && (!value || value.trim() === "")) {
      setErrors((prev) => ({ ...prev, title: t("validation.label_required") }));
    } else {
      setErrors((prev) => ({ ...prev, title: null }));
    }
  };

  const validateURL = (e) => {
    computeIsValid();
    if (submits === 0) return;

    const value = e.target.value;
    if (!value || value.trim() === "") {
      setErrors((prev) => ({ ...prev, url: t("validation.url_required") }));
    } else {
      setErrors((prev) => ({ ...prev, url: null }));
    }
  };

  return (
    <LabeledInput label={label}>
      <FormArrayInputWrapper
        helper={t("form.array.helper.link")}
        isValid={isValid}
        onAdd={handleInsert}
      >
        <TextField
          inputRef={labelRef}
          placeholder={labelPlaceholderText}
          fullWidth
          helperText={errors.title}
          error={!!errors.title}
          required={isLabelRequired}
          onChange={validateLabel}
        />
        <Spacer size={2}></Spacer>
        <TextField
          inputRef={urlRef}
          placeholder={urlPlaceholder}
          type="url"
          fullWidth
          helperText={errors.url}
          error={!!errors.url}
          onChange={validateURL}
        />
      </FormArrayInputWrapper>
    </LabeledInput>
  );
}

function FormArrayInputWrapper({
  children,
  helper,
  onAdd,
  isDisabled,
  isValid,
}) {
  return (
    <div className="input-area-wrapper">
      <div className="input-area">
        {children}
        <Typography variant="caption" fontStyle="italic">
          {helper}
        </Typography>
      </div>
      <IconButton
        onClick={onAdd}
        sx={{ height: "fit-content" }}
        disabled={isDisabled}
        className={isValid ? "add-button-pulse" : ""}
      >
        <EurekaIcon name="add" />
      </IconButton>
    </div>
  );
}

/**
 *
 * @param {Object} props
 * @param {'list' | 'chips'} [props.displayMode='list'] - The display mode for the items.
 * @param {'text' | 'url'} [props.variant='text'] - The variant of the display, either "text" or "url".
 * @param {import("react-hook-form").UseFieldArrayRemove} props.remove - Remove method from useFieldArray
 * @param {Array} props.items - Array of items to display
 *
 * @returns
 */
function FormArrayDisplay({
  displayMode = "list",
  variant = "text",
  items,
  remove,
}) {
  return (
    <div className="items-display">
      {displayMode === "list" && (
        <FormArray.List items={items} onDelete={remove} />
      )}
      {displayMode === "chips" && (
        <FormArray.Chips items={items} onDelete={remove} variant={variant} />
      )}
    </div>
  );
}

/**
 * Renders a list of items, each with a delete button.
 * @param {Object} props
 * @param {Array<FieldArrayItemRHF>} props.items - Array of objects, each containing at least a 'listGeneratedId' property.
 * @param {Function} props.onDelete - Function to call when deleting an item.
 * @returns {JSX.Element}
 */
function FormArrayList({ items, onDelete }) {
  return (
    <div className="items-list">
      {items.map((item, index) => (
        <div key={item.listGeneratedId} className="item-row">
          <div className="item-value">{item}</div>
          <div className="actions">
            <IconButton onClick={() => onDelete(index)}></IconButton>
          </div>
        </div>
      ))}
    </div>
  );
}

/**
 * Renders a list of items, each with a delete button.
 * @param {Object} props
 * @param {'text' | 'url'} props.variant - The variant of the chips, either "text" or "url".
 * @param {Array<FieldArrayItemRHF>} props.items - Array of objects, each containing at least a 'listGeneratedId' property.
 * @param {Function} props.onDelete - Function to call when deleting an item.
 * @returns {JSX.Element}
 */
function FormArrayChips({ items, variant, onDelete }) {
  const isUrlVariant = variant === "url";

  return (
    <div className="items-chips">
      {items.map((item, index) => {
        if (isUrlVariant) {
          return (
            <Tooltip key={item.listGeneratedId} title={item.url}>
              <Chip
                label={item.title}
                variant="outlined"
                icon={
                  <EurekaIcon
                    name="link"
                    fontSize="small"
                    sx={{ transform: "rotate(45deg)", color: "text.secondary" }}
                  />
                }
                clickable
                component={Link}
                to={item.url}
                openInNewTab
                onDelete={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  onDelete(index);
                }}
              />
            </Tooltip>
          );
        }
        return (
          <Chip key={item} label={item} onDelete={onDelete} variant={variant} />
        );
      })}
    </div>
  );
}

FormArray.TextInput = FormArrayTextInput;
FormArray.URLInput = FormArrayURLInput;
FormArray.Display = FormArrayDisplay;
FormArray.List = FormArrayList;
FormArray.Chips = FormArrayChips;
