export const baseUrls = {
  login: "/api/auth/login",
  logout: "/api/auth/logout",
  signup: "/api/auth/signup",
  forgotPassword: "/api/auth/forgot-password",
  resetPassword: "/api/auth/reset-password",
  me: "/api/auth/me",
  europeana: "/api/external/europeana",
  projects: "/api/projects",
  project: (projectId) => `/api/projects/${projectId}`,
  projectPopulated: (projectId) => `/api/projects/${projectId}/populated`,
  library: "/api/assets",
  libraryAsset: (assetId) => `/api/assets/${assetId}`,
  members: (projectId) => `/api/projects/${projectId}/members`,
  users: "/api/users",
  tours: "/api/tours",
  tour: (tourId) => `/api/tours/${tourId}`,
  pois: "/api/pois",
  poi: (poiId) => `/api/pois/${poiId}`,
  poiAssets: "/api/poi-assets",
  poiAsset: (assetId) => `/api/poi-assets/${assetId}`,
  localesCDN: (locale) => `https://flagcdn.com/${locale}/codes.json`,
};
