/** @const */
export const icons = {
  add: "add",
  arrowUp: "keyboard_arrow_up",
  arrowDown: "keyboard_arrow_down",
  archive: "archive",
  audio: "audio_file",
  back: "arrow_back",
  breadcrumb: "keyboard_arrow_right",
  browse: "folder_eye",
  chart: "bar_chart_4_bars",
  check: "check",
  checkCircle: "check_circle",
  close: "close",
  copy: "content_copy",
  decline: "trending_down",
  delete: "delete",
  document: "article",
  edit: "edit",
  error: "error",
  filter: "filter_list",
  gridView: "grid_view",
  growth: "trending_up",
  help: "help",
  home: "home",
  image: "image",
  info: "info",
  language: "language",
  link: "link",
  list: "list",
  map: "map",
  media: "perm_media",
  menu: "menu",
  model: "view_in_ar",
  openInNew: "open_in_new",
  palette: "palette",
  poi: "location_on",
  publish: "publish",
  reset: "replay",
  route: "route",
  save: "save",
  search: "search",
  settings: "settings",
  sort: "swap_vert",
  time: "schedule",
  tour: "tour",
  uploadImage: "add_photo_alternate",
  user: "person",
  users: "group",
  video: "videocam",
  visibility: "visibility",
};

/**
 * @typedef {keyof typeof icons} IconName
 */
