/** @const */
export const icons = {
  add: "add",
  arrowUp: "keyboard_arrow_up",
  arrowDown: "keyboard_arrow_down",
  archive: "archive",
  back: "arrow_back",
  breadcrumb: "keyboard_arrow_right",
  chart: "bar_chart_4_bars",
  check: "check",
  checkCircle: "check_circle",
  close: "close",
  copy: "content_copy",
  decline: "trending_down",
  delete: "delete",
  document: "article",
  edit: "edit",
  filter: "filter_list",
  growth: "trending_up",
  home: "home",
  image: "image",
  info: "info",
  map: "map",
  media: "perm_media",
  menu: "menu",
  model: "view_in_ar",
  poi: "location_on",
  publish: "publish",
  reset: "replay",
  route: "route",
  save: "save",
  search: "search",
  settings: "settings",
  sort: "swap_vert",
  time: "schedule",
  tour: "tour",
  user: "person",
  users: "group",
  video: "videocam",
  visibility: "visibility",
};

/**
 * @typedef {keyof typeof icons} IconName
 */
